Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	config.vm.define "desktop" do |desktop|
	config.vm.provision :shell, inline: <<-SHELL
	 sudo yum -y update
	 sudo yum -y install postgresql postgresql-contrib
	SHELL
	end
end
#aplicar usuario e criar o banco de dados via script para ser iniciado junto com o script*
