Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
		config.vm.define "desktop" do |desktop|
				config.vm.provision :shell, path: "banco.sh" 
	
	 desktop.trigger.after :up do |trigger|
      trigger.info = "Starting script"
      trigger.run = {path: "bscript.sh"}
	end
end
