Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	config.vm.define "desktop" do |desktop|
	config.vm.provision :shell, inline: <<-SHELL
	 sudo yum -y update
	 sudo yum -y install postgresql-server postgresql-contrib
	 sudo postgresql-setup initdb
	 sudo systemctl start postgresql
	 sudo systemctl enable postgresql
	 sudo adduser aluno 
	SHELL
	end
end
