Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	config.vm.define "desktop" do |desktop|
	config.vm.provision :shell, inline: <<-SHELL
	 sudo apt-get update
	 sudo apt-get install -y postgresql postgresql-contrib
	SHELL
	end
end
#criaçao de usuario
