Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	config.vm.define "desktop" do |desktop|
	config.vm.provision :shell, inline: <<-SHELL
	echo "INICIANDO" 
	sleep 5
	sudo yum -y update
	sudo yum -y install wget
	sudo yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
	sudo wget https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm
	sudo yum -y install pgdg-centos96-9.6-3.noarch.rpm epel-release
	sudo yum -y install postgresql96-server postgresql96-contrib
	sudo /usr/pgsql-9.6/bin/postgresql96-setup initdb
	sudo systemctl start postgresql-9.6
	sudo systemctl enable postgresql-9.6
	echo "Todos os processos foram concluidos"
	SHELL
	end
end
